name: SQL Lint

on:
  push:
    paths:
      - 'create_table.sql'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint SQL file
      uses: Bidaya0/sql-lint-in-action@v0.0.1
      with:
        path: 'create_table.sql'